In [5]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [6]:
import pandas as pd
from feature_store.feature_store import LocalFeatureStore

In [7]:
import pandas as pd
df=pd.read_csv("../data/processed/AQI_feature_engineered.csv")
df.head()

,datetime,AQI,CO,NO,NO2,O3,SO2,PM2_5,PM10,NH3,hour,day,month,weekday,AQI_change,AQI_rolling_avg
0,1970-01-01 00:00:01.783731600,3,67.63,0.00,0.68,38.67,0.74,14.64,61.21,0.24,0,1,1,Thursday,0.0,3.0
1,1970-01-01 00:00:01.783735200,3,68.75,0.01,0.88,38.99,0.81,14.09,58.51,0.25,0,1,1,Thursday,0.0,3.0
2,1970-01-01 00:00:01.783738800,3,70.31,0.06,1.07,40.05,0.90,13.57,55.94,0.23,0,1,1,Thursday,0.0,3.0
3,1970-01-01 00:00:01.783742400,3,71.19,0.12,1.03,43.18,0.95,13.26,55.49,0.20,0,1,1,Thursday,0.0,3.0
4,1970-01-01 00:00:01.783746000,3,71.06,0.14,0.80,47.91,0.95,12.99,53.78,0.18,0,1,1,Thursday,0.0,3.0

In [8]:
store=LocalFeatureStore()
store.save_features(df)

✅ Features saved successfully.

In [9]:
loadeddf=store.load_features()
loadeddf.head()

✅ Features loaded successfully.

,datetime,AQI,CO,NO,NO2,O3,SO2,PM2_5,PM10,NH3,hour,day,month,weekday,AQI_change,AQI_rolling_avg
0,1970-01-01 00:00:01.783731600,3,67.63,0.00,0.68,38.67,0.74,14.64,61.21,0.24,0,1,1,Thursday,0.0,3.0
1,1970-01-01 00:00:01.783735200,3,68.75,0.01,0.88,38.99,0.81,14.09,58.51,0.25,0,1,1,Thursday,0.0,3.0
2,1970-01-01 00:00:01.783738800,3,70.31,0.06,1.07,40.05,0.90,13.57,55.94,0.23,0,1,1,Thursday,0.0,3.0
3,1970-01-01 00:00:01.783742400,3,71.19,0.12,1.03,43.18,0.95,13.26,55.49,0.20,0,1,1,Thursday,0.0,3.0
4,1970-01-01 00:00:01.783746000,3,71.06,0.14,0.80,47.91,0.95,12.99,53.78,0.18,0,1,1,Thursday,0.0,3.0